
# "thing" is a string copied straight from SeaView. The program reads this
# string and sets up multiple sequences in a list, with the first sequence
# being the "target" sequence.
thing = """>Prophage 9W
GATGATTCGTTGTTGTTCCAGTCTGGGCCAATACAGTTTCTGCAAGATCTATTCTCTTTGATAGCACTTTTATTAGCCCTCTTCTCACTATTTCATATATTAGCCTCTTATTCTGAAACCTTACCTCTGATTTATTTGGATGAGCATTTACATCAACTTGATCATACGGTATCTCTAAGTGCAGCGCTGCAAAAGGATATCTATT-GTTTGGAATAAGGTCGTGATACGCATAACGAATTGCACCAATAAGTAGATTATCTTTAATTGGTCTACCATTAACAAATGTATAGATCTGGGTTGAATTGCTACGATTGACAGTAGGTTTACAGATGTATCCTGTAAGTCTAATGCCATCTTCTTCTTCACTAATTTGCAAAGAGTTTTCATGAAATTCTTCTTCTATTTCGCATAGCCTGCTAAATAATGAGGTCTGCTTAGCATACTTAAGAAGCTTCTTATTATCGGAGATAAGAGTAAACTCAATTCCATAATTGATCATTGCTAAGTTGTTTACAATATCAACAATGCTTTGTTTTTCTGCCCTTTCGGTTTTGAGAAATTTTAGTCTATTTGGTGTGGCAAAAAATAAATCTCGTACTTCAATATATGTTCCTATCGATAAAGGATAAGGAACAAGCTCTCCTATTTTTTCTCCCCCCTCATACCTTATAGACCATGCTTGATCTGCTTTGCTTGCCTTAGATGATAATTTTATTCTGCTTACTGCTGCAATTGAAGGCAAAGCTTCTCCTCTAAAGCCAAGATGCTTGATCTCTATCAATTCACTGTCACTCAATTTTGAAGTAGCATGGCGCATAAACGCAAGTTCTAAATCATCCTTTTTTACTCCGCTACCATCATCGATTACAGTAATGAGGTTACGCCCACCACTTTCTATCTTAATTTCTATCTCTGAGCTTCTCGCATCTATTGCATTTTCCACTAATTCCTTTACCACACTTGCAGGCCTTTCTATTACCTCTCCTGCTGCTATACGATTTATGGTTTTT-GTATCTAAAAGAACTATTGCCATTATAATG-TTGGTTTTTCTTTTACTGCTTGAGTTTGCTCCTCTCTCCATTTTTTTAATCTATCTGCAATTTCACTATTAGAAATCGACAGTATAGATGCAG
>9W_8
----------------------------------------------------------------------------------------------------------------CTGAAACCTTACCTCTGATTTATTTGGATGAGCATTTACATCAACTTGATCATACGGTATCTCTAAGTGCAGCGCTGCAAAAGGATATCTATT-GTTTGGAATAAGGTCGTGATACGCATAACGAATTGCACCAATAAGTAGATTATCTTTAATTGGTCTACCATTAACAAATGTATAGATCTGGGTTGAATTGCTACGATTGACAGTAGGTTTACAGATGTATCCTGTAAGTCTAATGCCATCTTCTTCTTCACTAATTTGCAAAGAGTTTTCATGAAATTCTTCTTCTATTTCGCATAGCCTGCTAAATAATGAGGTCTGCTTAGCATACTTAAGAAGCTTCTTATTATCGGAGATAAGAGTAAACTCAATTCCATAATTGATCATTGCTAAGTTGTTTACAATATCAACAATGCTTTGTTTTTCTGCCCTTTCGGTTTTGAGAAATTTTAGTCTATTTGGTGTGGCAAAAAATAAATCTCGTACTTCAATATATGTTCCTATCGATAAAGGATAAGGAACAAGCTCTCCTATTTTTTCTCCCCCCTCATACCTTATAGACCATGCTTGATCTGCTTTGCTTGCCTTAGATGATAATTTTATTCTGCTTACTGCTGCAATTGAAGGCAAAGCTTCTCCTCTAAAGCCAAGATGCTTGATCTCTATCAATTCACTGTCACTCAATTTTGAAGTAGCATGGCGCATAAACGCAAGTTCTAAATCATCCTTTTTTACTCCGCTACCATCATCGATTACAGTAATGAGGTTACGCCCACCACTTTCTATCTTAATTTCTATCTCTGAGCTTCTCGCATCTATTGCATTTTCCACTAATTCCTTTACCACACTTGCAGGCCTTTCTATTACCTCTCCTGCTGCTATACGATTTATGGTTTTT-GTATCTAAAAGAACTATTGCCATTATAATG-TTGGTTTTTCTTTTACTGCTTGAGTTTGCTCCTCTCTCCATTTTTTTAATCTATCTGCAATTT------------------------------
>9W_9
----------------------------------------------------------------------------------------------------------------CTGAAACCTTACCTCTGATTTATTTGGATGAGCATTTACATCAACTTGATCATACGGTATCTCTAAGTGCAGCGCTGCAAAAGGATATCTATT-GTTTGGAATAAGGTCGTGATACGCATAACGAATTGCACCAATAAGTAGATTATCTTTAATTGGTCTACCATTAACAAATGTATAGATCTGGGTTGAATTGCTACGATTGACAGTAGGTTTACAGATGTATCCTGTAAGTCTAATGCCATCTTCTTCTTCACTAATTTGCAAAGAGTTTTCATGAAATTCTTCTTCTATTTCGCATAGCCTGCTAAATAATGAGGTCTGCTTAGCATACTTAAGAAGCTTCTTATTATCGGAGATAAGAGTAAACTCAATTCCATAATTGATCATTGCTAAGTTGTTTACAATATCAACAATGCTTTGTTTTTCTGCCCTTTCGGTTTTGAGAAATTTTAGTCTATTTGGTGTGGCAAAAAATAAATCTCGTACTTCAATATATGTTCCTATCGATAAAGGATAAGGAACAAGCTCTCCTATTTTTTCTCCCCCCTCATACCTTATAGACCATGCTTGATCTGCTTTGCTTGCCTTAGATGATAATTTTATTCTGCTTACTGCTGCAATTGAAGGCAAAGCTTCTCCTCTAAAGCCAAGATGCTTGATCTCTATCAATTCACTGTCACTCAATTTTGAAGTAGCATGGCGCATAAACGCAAGTTCTAAATCATCCTTTTTTACTCCGCTACCATCATCGATTACAGTAATGAGGTTACGCCCACCACTTTCTATCTTAATTTCTATCTCTGAGCTTCTCGCATCTATTGCATTTTCCACTAATTCCTTTACCACACTTGCAGGCCTTTCTATTACCTCTCCTGCTGCTATACGATTTATGGTTTTT-GTATCTAAAA------------------------------------------------------------------------------------------------------------------
>9W_11
----------------------------------------------------------------------------------------------------------------------------------------------------------------ATCATACGGTATCTCTAAGTCCAGCGCTGCAAAAGGATATCTATTAGTTCGGAATAAGGTCGTGATACGCATAACGAATCGCACCAATAAGTAGATTATCTTTAATTGGTCTACCATTAACAAATGTATAGATCTGGGTTGAATCGCTACGATTGACAGTAGGTTTACAGATGTATCCTGTAAGTCTAATGCCATCTTCTTCTTCACTAATTTGCAAAGAGTTTTCATGAAATTCTTCTTCTATTTCGCATAGCCTGCTAAATAATGAGGTCTGCTTAGCATACTTAAGAAGCTTCTTATTATCGGAGATAAGAGTAAACTCAATTCCATAATTGATCATTGCTAAGTTGTTTACAATATCAACAATGCTTTGTTTTTCTGCCCTTTCGGTTTTGAGAAATTTTAGTCTATTTGGTGTGGCAAAAAATAAATCTCGTACTTCAATATATGTTCCTATCGATAAAGGATAAGGAACAAGCTCTCCTATTTTTTCTCCCCCCTCATACCTTATAGACCATGCTTGATCTGCTTTGCTTGCCTTAGATGATAATTTTATTCTGCTTACTGCTGCAATTGAAGGCAAAGCTTCTCCTCTAAAGCCAAGATGCTTGATCTCTATCAATTCACTGTCACTCAATTTTGAAGTAGCATGGCGCATAAACGCAAGTTCTAAATCATCCTTTTTTACTCCGCTACCATCATCGATTACGGTAATGAGGTTACGCCCACCACTTTCTATCTTAATTTCTATCTCTGAGCTTCTCGCATCTATTGCATTTTCCACTAATTCCTTTACCACACTTGCAGGCCTTTCTATTACCTCTCCTGCTGCTATACAATTTAAGGGTTTTTGTATCTAAAAGAACTATTGCATAAAAAAGGTTTGGTTTTTTTTTTACTGGTTGAATTTGCTCCTCTCTCCATTTTTTAAT-CTATCTGCATTTCCTAA--------------------------
>9W_12
---------------------------------------------------------------------------------------------------------------TCTGAAACCTTACCTCTGATTTATTTGGATGAGCATTTACATCAACTTGATCATACGGTATCTCTAAGTGCAGCGCTGCAAAAGGATATCTATT-GTTTGGAATAAGGTCGTGATACGCATAACGAATTGCACCAATAAGTAGATTATCTTTAATTGGTCTACCATTAACAAATGTATAGATCTGGGTTGAATTGCTACGATTGACAGTAGGTTTACAGATGTATCCTGTAAGTCTAATGCCATCTTCTTCTTCACTAATTTGCAAAGAGTTTTCATGAAATTCTTCTTCTATTTCGCATAGCCTGCTAAATAATGAGGTCTGCTTAGCATACTTAAGAAGCTTCTTATTATCGGAGATAAGAGTAAACTCAATTCCATAATTGATCATTGCTAAGTTGTTTACAATATCAACAATGCTTTGTTTTTCTGCCCTTTCGGTTTTGAGAAATTTTAGTCTATTTGGTGTGGCAAAAAATAAATCTCGTACTTCAATATATGTTCCTATCGATAAAGGATAAGGAACAAGCTCTCCTATTTTTTCTCCCCCCTCATACCTTATAGACCATGCTTGATCTGCTTTGCTTGCCTTAGATGATAATTTTATTCTGCTTACTGCTGCAATTGAAGGCAAAGCTTCTCCTCTAAAGCCAAGATGCTTGATCTCTATCAATTCACTGTCACTCAATTTTGAAGTAGCATGGCGCATAAACGCAAGTTCTAAATCATCCTTTTTTACTCCGCTACCATCATCGATTACAGTAATGAGGTTACGCCCACCACTTTCTATCTTAATTTCTATCTCTGAGCTTCTCGCATCTATTGCATTTTCCACTAATTCCTTTACCACACTTGCAGGCCTTTCTATTACCTCTCCTGCTGCTATACGATTTATGGTTTTT-GTATCTAAAAGAACTATTGCCATTATAATG-TTGGTTTTTCTTTTACTGCTTGAGTTTGCTCCTCTCTCCATTTTTT-----------------------------------------------
>9W_15
----------------------------------------------------------------------------------------------------------------------------------TTTATTTGGATGAGCATTTACATCAACTTGATCATACGGTATCTCTAAGTGCAGCGCTGCAAAAGGATATCTATT-GTTTGGAATAAGGTCGTGATACGCATAACGAATTGCACCAATAAGTAGATTATCTTTAATTGGTCTACCATTAACAAATGTATAGATCTGGGTTGAATTGCTACGATTGACAGTAGGTTTACAGATGTATCCTGTAAGTCTAATGCCATCTTCTTCTTCACTAATTTGCAAAGAGTTTTCATGAAATTCTTCTTCTATTTCGCATAGCCTGCTAAATAATGAGGTCTGCTTAGCATACTTAAGAAGCTTCTTATTATCGGAGATAAGAGTAAACTCAATTCCATAATTGATCATTGCTAAGTTGTTTACAATATCAACAATGCTTTGTTTTTCTGCCCTTTCGGTTTTGAGAAATTTTAGTCTATTTGGTGTGGCAAAAAATAAATCTCGTACTTCAATATATGTTCCTATCGATAAAGGATAAGGAACAAGCTCTCCTATTTTTTCTCCCCCCTCATACCTTATAGACCATGCTTGATCTGCTTTGCTTGCCTTAGATGATAATTTTATTCTGCTTACTGCTGCAATTGAAGGCAAAGCTTCTCCTCTAAAGCCAAGATGCTTGATCTCTATCAATTCACTGTCACTCAATTTTGAAGTAGCATGGCGCATAAACGCAAGTTCTAAATCATCCTTTTTTACTCCGCTACCATCATCGATTACAGTAATGAGGTTACGCCCACCACTTTCTATCTTAATTTCTATCTCTGAGCTTCTCGCATCTATTGCATTTTCCACTAATTCCTTTACCACACTTGCAGGCCTTTCTATTACCTCTCCTGCTGCTATACGATTTATGGTTTTT-GTATCTAAAAGAACTATTGCCATTATAATG-TTGGTTTTTCTTTTACTGCTTGAGTTTGCTCCTCTCTCCATTTTTTTAATCTATCTGCAATTTC-----------------------------
>9W_17
----------------------------------------------------------------------------------------------------------------------CCTTACCTCTGATTTATTTGGATGAGCATTTACATCAACTTGATCATACGGTATCTCTAAGTGCAGCGCTGCAAAAGGATATCTATT-GTTTGGAATAAGGTCGTGATACGCATAACGAATTGCACCAATAAGTAGATTATCTTTAATTGGTCTACCATTAACAAATGTATAGATCTGGGTTGAATTGCTACGATTGACAGTAGGTTTACAGATGTATCCTGTAAGTCTAATGCCATCTTCTTCTTCACTAATTTGCAAAGAGTTTTCATGAAATTCTTCTTCTATTTCGCATAGCCTGCTAAATAATGAGGTCTGCTTAGCATACTTAAGAAGCTTCTTATTATCGGAGATAAGAGTAAACTCAATTCCATAATTGATCATTGCTAAGTTGTTTACAATATCAACAATGCTTTGTTTTTCTGCCCTTTCGGTTTTGAGAAATTTTAGTCTATTTGGTGTGGCAAAAAATAAATCTCGTACTTCAATATATGTTCCTATCGATAAAGGATAAGGAACAAGCTCTCCTATTTTTTCTCCCCCCTCATACCTTATAGACCATGCTTGATCTGCTTTGCTTGCCTTAGATGATAATTTTATTCTGCTTACTGCTGCAATTGAAGGCAAAGCTTCTCCTCTAAAGCCAAGATGCTTGATCTCTATCAATTCACTGTCACTCAATTTTGAAGTAGCATGGCGCATAAACGCAAGTTCTAAATCATCCTTTTTTACTCCGCTACCATCATCGATTACAGTAATGAGGTTACGCCCACCACTTTCTATCTTAATTTCTATCTCTGAGCTTCTCGCATCTATTGCATTTTCCACTAATTCCTTTACCACACTTGCAGGCCTTTCTATTACCTCTCCTGCTGCTATACGATTTATGGTTTTT-GTATCTAAAAGAACTATTGCCATTATAATG-TTGGTTTTTCTTTTACTGCTTGAGTTTGCTCCTCTCTCCATTTTTTAA-TCTATCTGCAATTTCACTATT-----------------------
"""
Sequences = []
sequence = ""
nextsequence = False
for character in thing: # Checks the individual characters in the SeaView
    # fasta input to determine where the sequence starts and ends
    
    if nextsequence == True:
        sequence = sequence + character
    if character == "\n" and nextsequence == False:
        nextsequence = True
    elif character == "\n" and nextsequence == True:
        sequence = sequence[0:-1]
        nextsequence = False
        Sequences.append(sequence.upper())
        sequence = ""

# Ignoring the first sequence (Since that is the target), run through each
# sequence and compare the bases at that location. If the sample base is a
# dash while the target sequence isn't, its a gap. If the sample base isn't
# a dash while the target sequence is, its an extra. If the base simply isn't
# the same, its a difference. At each step, note down which bp location the
# misalignment ocurred at.

for Alignment in range(1,len(Sequences)):
    gaps = 0
    differences = 0
    extras = 0
    mistakes = []
# Endgaps and Endextras just ensures that extra gaps/extras aren't accounted
# for if its at the end of the sequence, as that is just due to the cleanup
# process. Additionally, dashes at the start of the sequence also aren't
# counted.
    endgaps = 0
    endextras = 0
    for i in range(0,len(Sequences[0])-1):
        StartFound = False
        if not Sequences[Alignment][i] == "-":
            StartFound = True
        if StartFound == True:
            if Sequences[Alignment][i] == "-" and not Sequences[0][i] == "-":
                gaps +=1
                endgaps +=1
                mistakes.append(i+1)
                endextras = 0
            elif Sequences[0][i] == "-" and not Sequences[Alignment][i] == "-":
                extras +=1
                endextras +=1
                mistakes.append(i+1)
                endgaps = 0
            elif not Sequences[Alignment][i] == Sequences[0][i]:
                differences +=1
                mistakes.append(i+1)
                endgaps = 0
                endextras = 0
            else:
                endgaps = 0
                endextras = 0
    if endgaps+endextras > 0:
        for i in range(0, endgaps + endextras):
            del mistakes[-1]
    #Once calculated, print all the necessary information for that sequence.
    print(f"Gaps: {str(gaps - endgaps)}\nDifferences: {str(differences)}\nExtras: {str(extras-endextras)}\nMistakes: {mistakes}\n\n")

                
            
    
